### ISSUE TITLE
有报错

### ISSUE THREAD

**Issue by BigAppleClass** [zhinghu/CatSeedLogin#54]
[06:02:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'l' in plugin CatSeedLogin v1.4.5-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at org.bukkit.craftbukkit.v1_21_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:419) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:341) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:328) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1860) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1836) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:164) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1319) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:210) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:138) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1298) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1291) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:147) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1248) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.x_(MinecraftServer.java:1258) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1101) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: location.world
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_21_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1043) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at org.bukkit.craftbukkit.v1_21_R2.entity.CraftEntity.teleport(CraftEntity.java:191) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at cc.baka9.catseedlogin.bukkit.CatScheduler.teleport(CatScheduler.java:28) ~[?:?]
        at cc.baka9.catseedlogin.bukkit.command.CommandLogin.lambda$onCommand$0(CommandLogin.java:45) ~[?:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at cc.baka9.catseedlogin.bukkit.command.CommandLogin.onCommand(CommandLogin.java:45) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 28 more
[06:02:48] [Craft Scheduler Thread - 4/INFO]: [CatSeedLogin] 缓存加载 2 个数据

**Comment by shulng** [comment]
> [06:02:48] [Server thread/ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'l' in plugin CatSeedLogin v1.4.5-SNAPSHOT at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_21_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at org.bukkit.craftbukkit.v1_21_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?] at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:419) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:341) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:328) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1860) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1836) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:164) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1319) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:210) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:138) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1298) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1291) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:147) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1248) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.x_(MinecraftServer.java:1258) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1101) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.lang.IllegalArgumentException: location.world at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?] at org.bukkit.craftbukkit.v1_21_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1043) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at org.bukkit.craftbukkit.v1_21_R2.entity.CraftEntity.teleport(CraftEntity.java:191) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231] at cc.baka9.catseedlogin.bukkit.CatScheduler.teleport(CatScheduler.java:28) ~[?:?] at cc.baka9.catseedlogin.bukkit.command.CommandLogin.lambda$onCommand$0(CommandLogin.java:45) ~[?:?] at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] at cc.baka9.catseedlogin.bukkit.command.CommandLogin.onCommand(CommandLogin.java:45) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?] ... 28 more [06:02:48] [Craft Scheduler Thread - 4/INFO]: [CatSeedLogin] 缓存加载 2 个数据

说一下插件版本
服务器版本
以及服务端

**Comment by shulng** [comment]
试试这个版本https://github.com/zhinghu/CatSeedLogin/actions/runs/12044584684
